CREATE TABLE `active_interviews` (
  `ACTIVE_INTERVIEW_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `INTERVIEW_ID` int(10) unsigned NOT NULL,
  `HOST_ID` int(10) unsigned NOT NULL,
  `PROPOSALS_OFFERS` bit(1) DEFAULT NULL,
  `JOB_OFFERED_BY_HOSTS` bit(1) DEFAULT NULL,
  `JOB_ACCEPTED_BY_AU-PAIR` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ACTIVE_INTERVIEW_ID`),
  KEY `INTERVIEW_ID_idx` (`INTERVIEW_ID`),
  KEY `HOST_ID_idx` (`HOST_ID`),
  CONSTRAINT `FK_ACTIVE_INTERVIEWS_HOST_ID` FOREIGN KEY (`HOST_ID`) REFERENCES `hostuser` (`host_id`),
  CONSTRAINT `FK_ACTIVE_INTERVIEWS_INTERVIEW_ID` FOREIGN KEY (`INTERVIEW_ID`) REFERENCES `interview_availability` (`interview_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
SELECT * FROM au_pair_management.active_interviews;