CREATE TABLE `address` (
  `ADDRESS_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` int(10) unsigned NOT NULL,
  `COUNTRY_CURRENCY_ID` int(10) unsigned NOT NULL,
  `ADDRESS_LINE1` varchar(45) NOT NULL,
  `CITY` varchar(45) NOT NULL,
  `POSTCODE` int(11) NOT NULL,
  PRIMARY KEY (`ADDRESS_ID`),
  KEY `PERSON_ID_idx` (`PERSON_ID`),
  KEY `COUNTRY_CURRENCY_ID_idx` (`COUNTRY_CURRENCY_ID`),
  CONSTRAINT `FK_ADDRESS_COUNTRY_CURRENCY_ID` FOREIGN KEY (`COUNTRY_CURRENCY_ID`) REFERENCES `country_currency` (`country_currency_id`),
  CONSTRAINT `FK_ADDRESS_PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
SELECT * FROM au_pair_management.active_interviews;