CREATE TABLE `contract` (
  `CONTRACT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `AU_PAIR_ID` int(10) unsigned NOT NULL,
  `HOST_ID` int(10) unsigned NOT NULL,
  `SIGNED_CONTRACT_IMAGE` binary(255) DEFAULT NULL,
  PRIMARY KEY (`CONTRACT_ID`),
  KEY `AU_PAIR_ID_idx` (`AU_PAIR_ID`),
  KEY `HOST_ID_idx` (`HOST_ID`),
  CONSTRAINT `FK_CONTRACT_AU_PAIR_ID` FOREIGN KEY (`AU_PAIR_ID`) REFERENCES `au_pair` (`au_pair_id`),
  CONSTRAINT `FK_CONTRACT_HOST_ID` FOREIGN KEY (`HOST_ID`) REFERENCES `hostuser` (`host_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
