CREATE TABLE `country_currency` (
  `COUNTRY_CURRENCY_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `COUNTRY_NAME` varchar(45) NOT NULL,
  `CURRENCY_NAME` varchar(45) NOT NULL,
  `CURRENCY_CODE` varchar(45) NOT NULL,
  UNIQUE KEY `COUNTRY_NAME_UNIQUE` (`COUNTRY_NAME`),
  UNIQUE KEY `COUNTRY_CURRENCY_ID_UNIQUE` (`COUNTRY_CURRENCY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=utf8;
