CREATE TABLE `hostuser` (
  `HOST_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` int(10) unsigned NOT NULL,
  `IS_SALARY_PROVIDED` bit(1) NOT NULL,
  `NUMBER_OF_KIDS` int(11) DEFAULT NULL,
  `AGE_OF_KIDS` int(11) DEFAULT NULL,
  `HAS_PHYSICAL_DISABILITY` bit(1) NOT NULL,
  PRIMARY KEY (`HOST_ID`),
  UNIQUE KEY `HOST_ID_UNIQUE` (`HOST_ID`),
  KEY `PERSON_ID_idx` (`PERSON_ID`),
  CONSTRAINT `FK_Host_PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
