CREATE TABLE `languages` (
  `LANGUAGE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` int(10) unsigned NOT NULL,
  `LANGUAGES` varchar(45) NOT NULL,
  `PROFICIENCY` varchar(45) NOT NULL,
  PRIMARY KEY (`LANGUAGE_ID`),
  KEY `PERSON_ID_idx` (`PERSON_ID`),
  CONSTRAINT `Fk_Language_PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
