CREATE TABLE `rating_feedback` (
  `RATING_FEEDBACK_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `HOST_ID` int(10) unsigned NOT NULL,
  `AU_PAIR_ID` int(10) unsigned NOT NULL,
  `RATINGS` int(11) NOT NULL,
  `COMMENTS` varchar(45) DEFAULT NULL,
  `RATEDBYHOST` bit(1) DEFAULT NULL,
  PRIMARY KEY (`RATING_FEEDBACK_ID`),
  KEY `AU_PAIR_ID_idx` (`AU_PAIR_ID`),
  KEY `FK_RATINGS_FEEDBACK_HOST_ID` (`HOST_ID`),
  CONSTRAINT `FK_RATINGS_FEEDBACK_AU_PAIR_ID` FOREIGN KEY (`AU_PAIR_ID`) REFERENCES `au_pair` (`au_pair_id`),
  CONSTRAINT `FK_RATINGS_FEEDBACK_HOST_ID` FOREIGN KEY (`HOST_ID`) REFERENCES `hostuser` (`host_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;



