CREATE DEFINER=`root`@`localhost` PROCEDURE `acceptProposalByAuPair`(
IN proposalID INT(10),
OUT activeIntId INT(10),
OUT hostId int(10),
OUT auPairId int(10))
BEGIN

SELECT ACTIVE_INTERVIEW_ID INTO activeIntId 
FROM proposals WHERE PROPOSAL_ID = proposalID;

UPDATE active_interviews SET JOB_ACCEPTED_BY_AU_PAIR = 'ACCEPTED' 
WHERE ACTIVE_INTERVIEW_ID = activeIntId; 

SELECT @INTERVIEW_ID :=  INTERVIEW_ID FROM active_interviews
WHERE ACTIVE_INTERVIEW_ID = activeIntId;

if @INTERVIEW_ID IS NOT NULL THEN

SELECT AU_PAIR_ID INTO auPairId FROM interview_availability
WHERE INTERVIEW_ID = @INTERVIEW_ID;
SELECT HOST_ID INTO hostId FROM active_interviews 
WHERE ACTIVE_INTERVIEW_ID = activeIntId;

INSERT INTO contract (AU_PAIR_ID,HOST_ID,SIGNED_CONTRACT_IMAGE,PROPOSAL_ID)
VALUES (auPairId,hostId,"",proposalID) ;

END IF;

END
