CREATE DEFINER=`root`@`localhost` PROCEDURE `viewProposal`(IN PERSONID INT,IN PERSONTYPE VARCHAR(45))
BEGIN
IF(PERSONTYPE='AUPAIR') THEN
#comment
SELECT PR.*,AI.*,H.*,CONCAT(HP.FIRST_NAME,' ',HP.LAST_NAME) HOSTNAME,IA.*,AP.*,CONCAT(P.FIRST_NAME,' ',P.LAST_NAME) AUPAIRNAME 
FROM PROPOSALS PR INNER JOIN ACTIVE_INTERVIEWS AI ON 
AI.ACTIVE_INTERVIEW_ID=PR.ACTIVE_INTERVIEW_ID INNER JOIN HOSTUSER H
ON H.HOST_ID=AI.HOST_ID INNER JOIN PERSON HP ON H.PERSON_ID=HP.PERSON_ID
INNER JOIN INTERVIEW_AVAILABILITY IA ON AI.INTERVIEW_ID=IA.INTERVIEW_ID
INNER JOIN AU_PAIR AP ON IA.AU_PAIR_ID=AP.AU_PAIR_ID INNER JOIN PERSON P ON AP.PERSON_ID=P.PERSON_ID
WHERE AP.PERSON_ID=PERSONID;
ELSEIF(PERSONTYPE='HOST') THEN
SELECT PR.*,AI.*,H.*,CONCAT(HP.FIRST_NAME,' ',HP.LAST_NAME) HOSTNAME,IA.*,AP.*,CONCAT(P.FIRST_NAME,' ',P.LAST_NAME) AUPAIRNAME 
FROM PROPOSALS PR INNER JOIN ACTIVE_INTERVIEWS AI ON 
AI.ACTIVE_INTERVIEW_ID=PR.ACTIVE_INTERVIEW_ID INNER JOIN HOSTUSER H
ON H.HOST_ID=AI.HOST_ID INNER JOIN PERSON HP ON H.PERSON_ID=HP.PERSON_ID
INNER JOIN INTERVIEW_AVAILABILITY IA ON AI.INTERVIEW_ID=IA.INTERVIEW_ID
INNER JOIN AU_PAIR AP ON IA.AU_PAIR_ID=AP.AU_PAIR_ID INNER JOIN PERSON P ON AP.PERSON_ID=P.PERSON_ID
WHERE HP.PERSON_ID=PERSONID;
END IF;
END
