CREATE TABLE `au_pair` (
  `AU_PAIR_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `PERSON_ID` int(10) unsigned NOT NULL,
  `HAS_VALID_VISA` bit(1) NOT NULL,
  `HAS_SALARY_EXPECTATION` bit(1) NOT NULL,
  `HAS_DRIVING_LICENSE` bit(1) NOT NULL,
  `HOBBIES` varchar(45) DEFAULT NULL,
  `SUPERVISES_CHILD_OF_AGE` varchar(10) NOT NULL,
  `EDU_QUALIFICATION` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`AU_PAIR_ID`),
  KEY `PERSON_ID_idx` (`PERSON_ID`),
  CONSTRAINT `PERSON_ID` FOREIGN KEY (`PERSON_ID`) REFERENCES `person` (`person_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
